Bugfix when build model with strict=False for load state dict
sinzlab/nnfabrik pull request #147
Opened 2023-12-04 21:38 UTC by KonstantinWilleke

2024-03-22 11:03 UTC, MaxFBurg requested changes

2024-03-22 11:03 UTC, MaxFBurg commented on nnfabrik/utility/nn_helpers.py
> +    strict=None,
```suggestion
    strict=True,
```

To keep default behavior

2024-03-22 11:03 UTC, MaxFBurg commented on nnfabrik/utility/nn_helpers.py
> +    if strict is None:
```suggestion
    if strict:
```

2024-03-22 11:03 UTC, MaxFBurg commented on nnfabrik/utility/nn_helpers.py
> +    model.load_state_dict(updated_model_dict, strict=(not ignore_missing) if strict is None else strict)
```suggestion
    model.load_state_dict(updated_model_dict, strict=(not ignore_missing) if strict is True else False)
```

2024-03-22 11:04 UTC, MaxFBurg commented
I think it would be cool and helpful to have this feature. I just added a review, @KonstantinWilleke could you have a quick look and commit the changes I requested? (if @ArneNx is fine with me reviewing instead?)

2024-03-22 11:13 UTC, ArneNx commented
Thank you for handling this Max. I don't use this anymore, so I'm fine if you take over on this review.

2024-04-09 09:03 UTC, MaxFBurg approved these changes

2024-04-09 09:03 UTC, merged